Check the map for all GameConstants MAP CONSTANTS
battlecode/battlecode22 pull request #53
Opened 2022-01-15 14:18 UTC by stefangimmillaro

Since the last one looked good I figured I would add the checks for the other constraints specified here https://github.com/battlecode/battlecode22/blob/main/engine/src/main/battlecode/common/GameConstants.java#L14

This one is a slightly more involved so please look carefully as I did this quickly (the same amount of time it took me to drink my morning 🍵) without specs.

Cheers and again thank you.

2022-01-15 14:21 UTC, stefangimmillaro commented
and thank you @wflms20110333 for the previous review!

2022-01-15 16:10 UTC, wflms20110333 requested changes
Looks good, thanks for doing this! We should've done this a long time ago probably lol...

2022-01-15 16:10 UTC, wflms20110333 commented on engine/src/main/battlecode/server/Server.java
> +        if (archonCount < GameConstants.MIN_STARTING_ARCHONS*2) {
style comment: can you put a space around the multiplication operator lol

2022-01-15 16:10 UTC, wflms20110333 commented on engine/src/main/battlecode/server/Server.java
> +        if (archonCount > GameConstants.MAX_STARTING_ARCHONS*2) {
ditto

2022-01-15 22:26 UTC, stefangimmillaro commented on engine/src/main/battlecode/server/Server.java
> +        if (archonCount < GameConstants.MIN_STARTING_ARCHONS*2) {
```suggestion
        if (archonCount < GameConstants.MIN_STARTING_ARCHONS * 2) {
```

2022-01-15 22:27 UTC, stefangimmillaro commented on engine/src/main/battlecode/server/Server.java
> +        if (archonCount > GameConstants.MAX_STARTING_ARCHONS*2) {
```suggestion
        if (archonCount > GameConstants.MAX_STARTING_ARCHONS * 2) {
```

2022-01-15 22:27 UTC, stefangimmillaro commented
@wflms20110333 done!

2022-01-15 22:33 UTC, stefangimmillaro commented
@wflms20110333 
<img width="721" alt="image" src="https://user-images.githubusercontent.com/1554858/149639628-49e19cbe-85fa-417a-8999-d865f8706528.png">
<img width="652" alt="image" src="https://user-images.githubusercontent.com/1554858/149639665-b74b7ded-bfe0-43cb-a477-b36387ebe5bf.png">

In case you didn't know about this feature, you can make suggestions in PRs. That way I can one-click merge them. I use this feature in my workplace, it improves PR resolution time. Thanks again.

2022-01-17 00:20 UTC, wflms20110333 commented
Oh wow I did not know about this feature. Seems cool, will keep in mind for the future!

2022-01-17 00:20 UTC, merged